name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  go:
    name: Test Go packages
    runs-on: ubuntu-latest
    container:
      image: golang:alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Test all modules
        run: |
          apk add --no-cache bash gcc g++ openssl-dev
          export GOFLAGS=-buildvcs=false
          go work init
          go work use -r .
          go test -v ./api/handlersTest/
